# Generated by Django 4.1.9 on 2023-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
